### ISSUE TITLE
file descriptor not closed

### ISSUE THREAD

**Issue by frochet** [torps/torps#7]
Hi Aaron ! 

https://github.com/torps/torps/blob/master/process_consensuses.py#L21 

I think a f.close() is missing at the end of the function ? I didn't set an unlimited number of open file descriptors on my OS and got some errors  :-)

**Comment by ajohnson-nrl** [comment]
Thanks for reporting this, Florentin! I have fixed the bug and pushed it. By the way, the latest archived consensuses on CollecTor use a new format that Stem doesn't recognize. In case you are using them, be warned, but the issue has been reported to Stem and will hopefully be fixed soon.

**Comment by frochet** [comment]
Thanks for that information :-) Hopefully, I am playing with old ones.
